#!/bin/bash
for filename in /media/p5/Funscript/hentai/uncensoredsd/original/do/*; do
    python deepmosaic.py --media_path $filename --mask_threshold 32 --model_path ./pretrained_models/mosaic/clean_hentai_video.pth --gpu_id 0
    mv $filename /media/p5/Funscript/hentai/uncensoredsd/original
    #echo $filename
done

