#!/bin/bash
for filename in /content/drive/video/*; do
    python deepmosaictemp.py --media_path $filename --mask_threshold 32 --model_path ./pretrained_models/mosaic/clean_hentai_video.pth --gpu_id 0
    #mv $filename /media/p5/Funscript/hentai/uncensoredsd/original
    dir="${filename%.*}"
    echo $dir
    mkdir $dir
    mv /content/DeepMosaics/tmp/DeepMosaics_temp/replace_mosaic $dir
    mv /content/DeepMosaics/tmp/DeepMosaics_temp/voice_tmp.mp3 $dir
    mv /content/DeepMosaics/result /content/drive
    cd /content/drive
    mv $dir ./
    rm -rf /content/DeepMosaics/tmp/DeepMosaics_temp
    #echo $filename
done

